"""
Django settings for auth_service project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ
from datetime import timedelta
from utils.helper import load_key


env = environ.Env(DEBUG=(bool, False))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Load environment variables from .env file
environ.Env.read_env(env_file=BASE_DIR / "config" / "main.env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# --- Security ---
SECRET_KEY = env("DJANGO_SECRET_KEY")
DEBUG = env.bool("DJANGO_DEBUG", default=False)
ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=[])


# Application definition

INSTALLED_APPS = [
    # Auth and security
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "auth_manager.apps.AuthManagerConfig",
    
    # "utils.apps.UtilsConfig",
    
    "utils.apps.UtilsConfig",
    "users.apps.UsersConfig",
    "core.apps.CoreConfig",
    "corsheaders",
    
    # System apps
    "api.apps.ApiConfig",
    'phonenumber_field',
    'django_countries',
    
     # django apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]


MIDDLEWARE = [
    # Custom Middleware
    "auth_manager.auth.middleware.JWTAuthenticationMiddleware",  # Custom Auth Middleware
    "corsheaders.middleware.CorsMiddleware",
    
    # Django Middleware
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "auth_service.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "auth_service.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {"default": env.db()}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# CORS settings# --- CORS (Optional) ---
# CORS_ALLOW_ALL_ORIGINS = True  # Caution in production
CORS_ALLOW_CREDENTIALS = True

# --- Logging (Professional Setup) ---
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles/auth"

# STATICFILES_DIRS = [BASE_DIR / "assets"]

# Maximum upload size (in bytes)
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10 MB (in-memory before streamed to disk)


MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media/auth"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# =====================================> Authentication Configs <===============================================#

# Service Configurations

AUTH_USER_MODEL = "users.User"  # Custom User Model
AUTH_URL = env("AUTH_URL", default="http://localhost:8080/api/v1/auth/")

LOGIN_URL = env("LOGIN_URL", default="http://localhost:8080/api/v1/auth/login/")


# Django Backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend', 
    'auth_manager.auth.backends.JWTAuthenticationBackend',  # Custom JWT Authentication Backend
]

# Rest Framework
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "auth_manager.auth.UserJWTAuthentication",  
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "auth_manager.auth.permissions.IsAuthenticated",
        ),
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
}


# Define key paths
user_keys_path = BASE_DIR / "keys"
service_keys_path = user_keys_path / "micro"

# Load keys for users
PRIVATE_KEY = load_key(user_keys_path / "private.pem")
PUBLIC_KEY = load_key(user_keys_path / "public.pem")

SIMPLE_JWT = {
    # 🔐 Cryptographic Setup
    "ALGORITHM": "RS256",
    "SIGNING_KEY": PRIVATE_KEY,  # Use private key for signing
    "VERIFYING_KEY": PUBLIC_KEY,  # Use public key for verification
    # 🕒 Token Lifetime Settings
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "TOKEN_OBTAIN_SERIALIZER": "auth_manager.auth.serializers.TokenObtainPairSerializer",
    "SLIDING_TOKEN_OBTAIN_SERIALIZER": "auth_manager.auth.serializers.TokenObtainSlidingSerializer",
}
